services:
 dbtpostgres:
   container_name: dbtpostgres
   image: postgres:17
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
     - ./scripts:/var/scripts
   env_file:
     - .env
 dbt:
   container_name: dbt
   image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
   platform: linux/amd64
   build: .
   volumes:
     - ./dbt:/usr/app/dbt
   ports:
     - "8080:8080"
   environment:
     DBT_PROFILES_DIR: /usr/app/dbt
     DBT_TARGET: dev
   depends_on:
     - dbtpostgres
   command: ["run"]

volumes:
   postgres_data:
